/**
 * Node modules
 */
import dotenv from 'dotenv';

dotenv.config();
/**
 * Constants
 */
const _1H_IN_MILLISECONDS = 1000 * 60 * 60;
const _7DAYS_IN_MILLISECONDS = 1000 * 60 * 60 * 24 * 7;

const config = {
  PORT: process.env.PORT!,
  NODE_ENV: process.env.NODE_ENV!,

  LOGTAIL_SOURCE_TOKEN: process.env.LOGTAIL_SOURCE_TOKEN!,
  LOGTAIL_INGESTING_HOST: process.env.LOGTAIL_INGESTING_HOST!,

  WINDOW_MS: _1H_IN_MILLISECONDS,

  MONGO_CONNECTION_URI: process.env.MONGO_CONNECTION_URI!,

  WHITELISTED_EMAILS: process.env.WHITELISTED_EMAILS,

  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET!,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET!,
  COOKIE_MAX_AGE: _7DAYS_IN_MILLISECONDS,
  JWT_PASSWORD_RESET_SECRET: process.env.JWT_PASSWORD_RESET_SECRET!,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET
};

export default config;